{% set name = "tatsu" %}
{% set version = "4.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/neogeny/TatSu/archive/v{{ version }}.tar.gz
  sha256: db392dffa3a847f748490e7dc5e4a37c6004aa5b4712a8b122ad3fdf43676a3e

build:
  number: 0
  entry_points:
    - tatsu = tatsu:main
    - g2e = tatsu.g2e:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - pytest-runner

  run:
    - python
    - pytest-runner

test:
  imports:
    - tatsu
    - tatsu.codegen
    - tatsu.g2e

  commands:
    - tatsu --help

about:
  home: https://github.com/neogeny/tatsu
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: TatSu takes a grammar in a variation of EBNF as input, and outputs a memoizing PEG/Packrat parser in Python.
  doc_url: https://tatsu.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - marcelotrevisani
