travis:
  secure:
    BINSTAR_TOKEN: R7k3Yw4F9Sku+d32JvwBGpn8nyuHe2CdBZy7qU7ON7i9yRzRE/XbsSYWBwEJ5zvyQBYHN8M5RurU8jWxIBMCMC3aqzciTf5DE/o6G3H0guDiQTIlQYqSG5U7K3OIMWYc8PYkTlSo/67GQeAWV6lbQcmNXsCPFPJvlM9t/itYzrJPTGph479cigTrM8Vm9DZcbpvpImwMxMGQS3tkJt2amazzHC2F+hTYQM5xA80yX2qLgNDNltasA/+7+jeYZsPCqgAZEy1mjtD4AiFJC9yT2qcxZI5L7s15I79TkcISKk5bUda+EJJ+h8wXTDab/1ZqOu5P74lgmExgk+bgaHdZngwlYN4bElN3lDxuz7c2iGdEWV9RHdx2QRYm96lRsWmfZfLTzs6zCHPTyG6xjaQpFMMReVhI1+iKZOcarZIQt5fE3bCqZqx2hDtSrOoAz5R+LeBYdLyD/8sH5uOpCx8HpmINI6PRLjxt12ctre+m1iyHUZhZi7dWFqelib8GLacJ/78dwf3Heyg8jMmjsJ+snG23W7FrROFiue3xLtVGdfYNH/evR3gex6Ocsj1EZaT6TgQCEs1fuBx6lahKTJGGAHqdD5AJmqDsu+eVImKmooM9Tjj6LPKPd9CMe9Af1YAWea8pHRxWKKsBycqYIpCwROi1He4QqxKsyLS0a0kQOSs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
